### ISSUE TITLE
Vault API reachable task fails when proxy env variables are defined

### ISSUE THREAD

**Issue by theodore86** [dockpack/ansible-vault#252]
Hi,

At the end of the role the task **Vault API reachable?** could potentially fail when **http_proxy** or **https_proxy** environment variables have been set during the actual host configuration, is it feasible (?) to:

1. Set this task optional - using the ``when: {{ validate_vault_api | bool }}``
2. or for the ``uri`` module we could set the option ``use_proxy={{ use_proxy_during_api_reachable_check | bool }}``

I could implement it and perform an pull request.

```
# This should succeed regardless of seal state
- name: Vault API reachable?
  # Attempt to help with long lines > 160 issues
  vars:
    vault_addr_protocol: "{{ vault_tls_disable | ternary('http', 'https') }}"
  uri:
    validate_certs: "{{ validate_certs_during_api_reachable_check | bool }}"
    url: "{{ vault_addr_protocol }}://{{ vault_hostname | default(vault_addr, true) }}:{{ vault_port }}/v1/sys/health"
    method: GET
    # 200 if initialized, unsealed, and active
    # 429 if unsealed and standby
    # 472 if data recovery mode replication secondary and active
    # 473 if performance standby
    # 501 if not initialized
    # 503 if sealed
    # See: https://www.vaultproject.io/api/system/health.html
    status_code: 200, 429, 472, 473, 501, 503
    body_format: json
  register: check_result
  retries: 6
  until: check_result is succeeded
  delay: 10
  changed_when: false
  tags:
    - check_vault
```

Thanks,
Theo G.
