### ISSUE TITLE
Windows installation

### ISSUE THREAD

**Issue by RoyzLevy** [dockpack/ansible-vault#304]
I've been looking for a windows installation for vault through ansible and did not find one as stated in the README in the community.
As a results I've been working on windows installation for vault through ansible role and wanted to check if this is needed.

**Comment by gardar** [comment]
Since the Consul role has Windows support I think it would be safe to say that a PR would be welcome, the lack of Windows support in this role is probably just due to the fact none of the contributors so far have needed it.

**Comment by bbaassssiiee** [comment]
```yaml
---
- name: Install HashiCorp Vault using Chocolatey
  hosts: windows
  tasks:
    - name: Install Chocolatey
      ansible.windows.win_chocolatey:
        name: chocolatey
        state: present
      become: true

    - name: Install HashiCorp Vault
      ansible.windows.win_chocolatey:
        name: vault
        state: present
      become: true

    - name: Verify Vault installation
      ansible.windows.win_command:
        command: vault --version
      register: vault_version_output

    - name: Output installed Vault version
      ansible.builtin.debug:
        msg: "Installed Vault version: {{ vault_version_output.stdout }}"
```
